@startuml

package "<LANG>parser" {
Lexer    <..  Parser
Parser   <..  Listener
Parser   <..  Visitor
Listener <|.. BaseListener
Visitor  <|.. BaseVisitor

Class Parser {

}
Class Lexer {

}

Interface Visitor<T> {
    visit<rule>()
}
Interface Listener {
    enter<rule>()
    exit<rule>()
}

Class BaseVisitor<T> {
}
Class BaseListener {
}

}

package "graph" {
Edge   o-- BaseGraph
Vertex o-- BaseGraph
BaseGraph <|.. CDG
BaseGraph <|.. SDG
VertexType <-- Vertex
EdgeType <-- Edge
SDG --> CDG

abstract Class BaseGraph
Class Vertex
Class Edge
Class CDG
Class SDG
enum VertexType
enum EdgeType

}


package "application" {

ParseTreeListener     <|-- ListenerSpec
ParseTreeVisitor      <|-- VisitorSpec
BaseListener <|-- ListenerSpec
BaseVisitor  <|-- VisitorSpec

Interface ParseTreeListener {
}
Interface ParseTreeVisitor<T> {
}


Class ListenerSpec {
}
Class VisitorSpec<T> {
}

GraphBuilder ..> BaseGraph

GraphBuilder <|.. CDGBuilder
GraphBuilder <|.. SDGBuilder

GraphBuilder ..> ParseTreeListener
GraphBuilder ..> ParseTreeVisitor

Grader --> SDG

abstract GraphBuilder

Class CDGBuilder
Class SDGBuilder
Class Grader


}


@enduml